### ISSUE TITLE
[任务] 文章翻译：现有开源软件许可合规工具

### ISSUE THREAD

**Issue by tedliu1** [kaiyuanshe/ONES#101]
现有开源软件许可合规工具
原文：https://oss-compliance-tooling.org/Tooling-Landscape/OSS-Based-License-Compliance-Tools/
译文：【腾讯文档】现有开源软件许可合规工具
https://docs.qq.com/doc/DZUtQanFaYk9ucUpI

**Comment by wangleo61** [comment]
Thanks Ted,Good to know.

Leo
发件人: Ted ***@***.***>
发送时间: Sunday, May 29, 2022 5:33 PM
收件人: ***@***.***>
抄送: ***@***.***>
主题: [kaiyuanshe/ONES] [任务] 文章翻译：现有开源软件许可合规工具 (Issue #101)


现有开源软件许可合规工具
原文：https://oss-compliance-tooling.org/Tooling-Landscape/OSS-Based-License-Compliance-Tools/
译文：【腾讯文档】现有开源软件许可合规工具
https://docs.qq.com/doc/DZUtQanFaYk9ucUpI

―

**Comment by tedliu1** [comment]
谢谢，还有一篇大号的论文正在翻译中

Ted Liu 
 
  2022 年 5 月 31 日周二 ***@***.***> 写道：   


感谢Ted老师，这篇写得真棒~
