### ISSUE TITLE
[会议] 2022 年 10 月 09 日第十二次线上工作会议

### ISSUE THREAD

**Issue by will-ww** [kaiyuanshe/ONES#111]
ONES Group 的双周例会重新启动，本次会议开始，庄表伟老师将启动”开源学“的学术研究活动，并计划在11月份的某个时间，召开《第一届开源学年会》，正好借本次双周例会听听大家的建议~

主持人：李小明 @Nliver

会议时间：2022 年 10 月 09 日 21:00 - 22:00（北京标准时间）

会议链接：
https://meeting.tencent.com/dm/EF2idWj9VloB
#腾讯会议（周期性）：685-1461-5121

会议内容：
- ONES Group 双周例会重启与后续安排（15 分钟）@will-ww
- 《第一届开源学年会》筹备（15 分钟）@zhuangbiaowei
- 自由讨论（整个会议控制在1个小时之内）

**Comment by will-ww** [comment]
在第一部分：ONES Group 双周例会重启与后续安排中，准备分享如下几个内容

![image](https://user-images.githubusercontent.com/15010826/194756660-a3f19327-b6a4-4271-86d1-5899d48f4d87.png)

1. 开源治理系列标准：即将发布（解读）
- 《信息技术 开源 开源概览与术语》
- 《信息技术 开源治理 第1部分：总体框架》
- 《信息技术 开源治理 第4部分：社区治理与运营 》

2. OSPO工具：https://github.com/X-lab2017/open-certified
3. OSPO China Landscape（延后）
4. 行业 OSPO 联盟（金融、汽车）
5. OSPO 相关标准的提议
- OSPO 胜任力模型与评估

**Comment by wangleo61** [comment]
期待

**Comment by zhuangbiaowei** [comment]
【腾讯文档】第一届开源学年会策划

https://docs.qq.com/doc/DUnNjZmVuRkxZVENr

**Comment by will-ww** [comment]
> 【腾讯文档】第一届开源学年会策划
> 
> https://docs.qq.com/doc/DUnNjZmVuRkxZVENr

我们实验室可以贡献一个子话题：开源测量与评估

**Comment by will-ww** [comment]
庄老师的开源学想干的，我们前面有过类似的思考，开源纲目：https://github.com/X-lab2017/open-research/tree/main/Opendium

**Comment by frank-zsy** [comment]
OSPO 相关的框架和理论研究非常有必要，对 OSPO 的标准化构建与职责范围有重要意义，我这里抛砖引玉

![image](https://user-images.githubusercontent.com/8512426/194984688-8ef2ea32-d447-4685-af01-2e58cee35841.png)

**Comment by will-ww** [comment]
这个太棒了，下次分享呀~  :-)

**Comment by wangleo61** [comment]
<img width="1058" alt="Screen Shot 2022-10-12 at 08 51 22" src="https://user-images.githubusercontent.com/62591087/195224238-c9bd83d8-3625-4fb4-a12e-969169c1a3d3.png">

**Comment by wangleo61** [comment]
<img width="553" alt="Picture1" src="https://user-images.githubusercontent.com/62591087/195224428-81efde49-3454-4576-a8de-536a076cb902.png">
<img width="858" alt="Picture2" src="https://user-images.githubusercontent.com/62591087/195224466-3e7dec99-e5dd-4e12-932b-2b271f24abc0.png">

**Comment by wangleo61** [comment]
> 这个太棒了，下次分享呀~ :-)

Frank这个图太精彩了

**Comment by wangleo61** [comment]
> OSPO 相关的框架和理论研究非常有必要，对 OSPO 的标准化构建与职责范围有重要意义，我这里抛砖引玉
> 
> ![image](https://user-images.githubusercontent.com/8512426/194984688-8ef2ea32-d447-4685-af01-2e58cee35841.png)

使用开源可否考虑加入 “漏洞” 以及“社区的健康度”等考量指标

**Comment by frank-zsy** [comment]
> > OSPO 相关的框架和理论研究非常有必要，对 OSPO 的标准化构建与职责范围有重要意义，我这里抛砖引玉
> 
> 使用开源可否考虑加入 “漏洞” 以及“社区的健康度”等考量指标

是的，在使用开源选型和研发管理这块应该需要一些指导的
