### ISSUE TITLE
[会议] 2023 年 02 月 12 日第十四次线上工作会议

### ISSUE THREAD

**Issue by Nliver** [kaiyuanshe/ONES#115]
本次会议是开源战略研究组（ONES Group）的 2023 年第一次会议。

# 会议议程：

拟定议题有：

1. ONES Group 2023年年度工作计划 @will-ww 

2. 一个基于markdown，生成各种格式的文档的工具，比如wiki、Blog、Book、Slide等等。就是基于上次的OSS-Book，产生的一些扩展 @zhuangbiaowei 

~3. 开源社的社区激励研究与实践 @郭浩赟~
(讲师临时有事儿，下次周会分享)

# 会议链接：

李小明 邀请您参加腾讯会议
会议主题：开源战略组ONES Group第十四次线上工作会议
会议时间：2023/02/12 21:00-22:30 (GMT+08:00) 中国标准时间 - 北京

点击链接入会，或添加至会议列表：
https://meeting.tencent.com/dm/Ez1wuXQpl3nP

#腾讯会议：289-973-102

复制该信息，打开手机腾讯会议即可参与

# 参会须知：
 - ONES Group工作组会议周期为双周一次，下一次会议时间预计在2023年2月26日
 - 入会前请提前寻找一个安静的场地，如果人在外面，建议保持静音
 - 本次会议信息网络公开，如有新参加的老师同学，请简单做个自我介绍

**Comment by will-ww** [comment]
今天的 PPT，可以提前了解下~

[2023 ONES Group 发展.pdf](https://github.com/kaiyuanshe/ONES/files/10715889/2023.ONES.Group.pdf)

**Comment by zhuangbiaowei** [comment]
[Markdown.world.pptx](https://github.com/kaiyuanshe/ONES/files/10716179/Markdown.world.pptx)
这个PPT，介绍了我在markdown方面的工作。
