### ISSUE TITLE
[年度成果] OSPOChina Landscape

### ISSUE THREAD

**Issue by will-ww** [kaiyuanshe/ONES#15]
也许通过 ONES Group 平台，今年能够迭代出一版 OSPOChina Landscape

![image](https://user-images.githubusercontent.com/15010826/157351407-d0b9a690-34bc-487e-bd64-7b3d1caa36e6.png)

欢迎大家前来讨论~

**Comment by TechQuery** [comment]
开源社官网的**中国开源地图**已实现类似功能，ONES 整理好数据即可快速复制上线一份：
- 原始 issue：kaiyuanshe/kaiyuanshe.github.io#61
- 最终效果：https://kaiyuanshe.cn/organization/landscape

**Comment by TechQuery** [comment]
如果不想强依赖 Netlify 云服务基础设施，就只能把官方代码重写为 React，来嵌入开源社官网目前的 Next.js 架构：
https://github.com/cncf/landscapeapp/tree/master/src

**Comment by TechQuery** [comment]
若用 CNCF 开发的新版 https://github.com/cncf/landscape2 ，有两种方式：

- 官方静态数据用法：https://github.com/cncf/landscape2?tab=readme-ov-file#usage
- 自研动态数据用法：https://github.com/cncf/landscape2/tree/main/ui/webapp

**Comment by Nliver** [comment]
> 若用 CNCF 开发的新版 https://github.com/cncf/landscape2 ，有两种方式：
> 
> * 官方静态数据用法：https://github.com/cncf/landscape2?tab=readme-ov-file#usage
> * 自研动态数据用法：https://github.com/cncf/landscape2/tree/main/web

我在周会上的建议是用landscape2，不过目前看是基于Rust重构的，我需要再看一段时间，他们是怎么做的
