### ISSUE TITLE
[会议] 2022年3月13日 第一次线上工作会议

### ISSUE THREAD

**Issue by will-ww** [kaiyuanshe/ONES#4]
3月13日（周日），晚上 9:00~9:30，第一次正式会议

参加人员：发起成员 + 首批成员

议题：ONES Group 的成立愿景、目标、工作机制、年度计划

方式：待定

欢迎大家添加内容~

**Comment by tedliu1** [comment]
收到。

Ted Liu 
 
  2022 年 3 月 6 日周日 10:57，Will ***@***.***> 写道：   


3月13日（周日），晚上 9:00~9:30，第一次正式会议

参加人员：发起成员 + 首批成员

议题：ONES Group 的成立愿景、目标、工作机制、年度计划

方式：待定

欢迎大家添加内容~

**Comment by LinuxSuRen** [comment]
是不是可以考虑提前把会议链接放出来，大家加到日历中，也方便时间安排、不容易忘记。

**Comment by will-ww** [comment]
是的，会的，我们明天就更新下~

**Comment by will-ww** [comment]
会议主题：双周 ONES 会议
会议时间：2022/03/13 21:00-21:30(GMT+08:00) 中国标准时间 - 北京
重复周期：2022/03/13-2024/01/28 21:00-21:30, 每两周 (周日)

点击链接入会，或添加至会议列表：
https://meeting.tencent.com/dm/2URNQRhq4xru

#腾讯会议：685-1461-5121

手机一键拨号入会
+8675536550000,,68514615121# (中国大陆)
+85230018898,,,2,68514615121# (中国香港)

根据您的位置拨号
+8675536550000 (中国大陆)
+85230018898 (中国香港)

**Comment by will-ww** [comment]
第一次会议的视频已发布：https://www.bilibili.com/video/BV11i4y1C7v2

等公众号文章发布了，就可以考虑把整个完整的信息结构化起来了~

**Comment by will-ww** [comment]
新闻稿正式发布：https://mp.weixin.qq.com/s/nkVKp8ayvPBlp4Dd38_lKw

感谢大家支持，本 issue 正式 close ~

**Comment by Nliver** [comment]
会议报道：https://mp.weixin.qq.com/s/nkVKp8ayvPBlp4Dd38_lKw
会议回放：https://www.bilibili.com/video/BV11i4y1C7v2
