### ISSUE TITLE
[任务] 文章翻译：How an OSPO Can Help Secure Your Software Supply Chain

### ISSUE THREAD

**Issue by will-ww** [kaiyuanshe/ONES#40]
小明推荐的一篇文章，值得翻译，有兴趣的来认领哈~

https://thenewstack.io/how-an-ospo-can-help-secure-your-software-supply-chain/

**Comment by will-ww** [comment]
同时，我们可能需要一个翻译的流程，看看是否有人可以来帮忙设计一个~

@zhuangbiaowei @tedliu1

**Comment by wangleo61** [comment]
翻译算我一个，这个非常不错哈

**Comment by zhuangbiaowei** [comment]
可以这样试试：
1. 在咱们这个项目下，放一个目录，就是翻译文档
2. 分为en/ zh/两个子目录
3. 愿意参与翻译的人，可以fork咱们的仓库，然后将英文目录下的文件，翻译到中文目录下，以同名方式存放
4. 大家可以审查提交的PR，并一起完善，也可以提交新的PR，一起来修订。
5. 另外做一个目录，是ONES项目组的官网，里面的内容会生成静态页面展示出来

这个事情，可以请水歌帮忙搭建一下。

**Comment by will-ww** [comment]
> 可以这样试试：
> 
> 1. 在咱们这个项目下，放一个目录，就是翻译文档
> 2. 分为en/ zh/两个子目录
> 3. 愿意参与翻译的人，可以fork咱们的仓库，然后将英文目录下的文件，翻译到中文目录下，以同名方式存放
> 4. 大家可以审查提交的PR，并一起完善，也可以提交新的PR，一起来修订。
> 5. 另外做一个目录，是ONES项目组的官网，里面的内容会生成静态页面展示出来
> 
> 这个事情，可以请水歌帮忙搭建一下。

Good idea，赞同~

**Comment by zhuangbiaowei** [comment]
【腾讯文档】How an OSPO Can Help Secure Your Software Supply Chain
https://docs.qq.com/doc/DUndhYmJkY2tpS1hp

借助DeepL整了一个初稿，大家可以先一起修订一下。

**Comment by wangleo61** [comment]
来啦，表哥动作好快呀，点赞

**Comment by zhuangbiaowei** [comment]
多谢 @wangleo61 ，我已经基本上按照你的意见修改了一遍。 再看看其他人，有没有修订的建议。

**Comment by will-ww** [comment]
太给力了，优秀~

**Comment by wangleo61** [comment]
> 多谢 @wangleo61 ，我已经基本上按照你的意见修改了一遍。 再看看其他人，有没有修订的建议。

表哥给力，很荣幸哈

**Comment by wangleo61** [comment]
> 太给力了，优秀~

哇，这种开放式协作得效率太高了，我中毒了

**Comment by wangleo61** [comment]
> 多谢 @wangleo61 ，我已经基本上按照你的意见修改了一遍。 再看看其他人，有没有修订的建议。

表哥给力哈，我又reveiew了一遍，添加了一个注释等你有空看看哈

**Comment by zhuangbiaowei** [comment]
> > 多谢 @wangleo61 ，我已经基本上按照你的意见修改了一遍。 再看看其他人，有没有修订的建议。
> 
> 表哥给力哈，我又reveiew了一遍，添加了一个注释等你有空看看哈

这样协作很爽，我也已经都回复了

**Comment by wangleo61** [comment]
这个效率太高了

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Nliver** [comment]
> 【腾讯文档】How an OSPO Can Help Secure Your Software Supply Chain https://docs.qq.com/doc/DUndhYmJkY2tpS1hp
> 
> 借助DeepL整了一个初稿，大家可以先一起修订一下。

收到，我来安排排期发布~

**Comment by wangleo61** [comment]
给力


发件人: ***@***.***>
发送时间: Thursday, March 31, 2022 8:26 PM
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [kaiyuanshe/ONES] [任务] 文章翻译：How an OSPO Can Help Secure Your Software Supply Chain (Issue #40)


【腾讯文档】How an OSPO Can Help Secure Your Software Supply Chain https://docs.qq.com/doc/DUndhYmJkY2tpS1hp

借助DeepL整了一个初稿，大家可以先一起修订一下。

收到，我来安排排期发布~

―

**Comment by will-ww** [comment]
太棒了！

**Comment by Nliver** [comment]
这篇文章已经发布了哈：https://mp.weixin.qq.com/s/1rVLSbm33B-Av8OFnT7i7A
