### ISSUE TITLE
[会议] 2022 年 3 月 27 日第二次线上工作会议 

### ISSUE THREAD

**Issue by will-ww** [kaiyuanshe/ONES#44]
议题持续征集中：

1. 开源善治理首创行动分享
- 提议人：@will-ww
- 主讲人：@will-ww （15分钟）

2. SPDX 分享（15分钟）
- 主讲人： @wangleo61 

3. ONES 日常事务（3分钟）

欢迎大家报名~

**Comment by wangleo61** [comment]
好的，我准备一下，下次分享哈

**Comment by wangleo61** [comment]
@will-ww 我可以花15分钟跟大家分享SPDX哈

**Comment by will-ww** [comment]
> @will-ww 我可以花15分钟跟大家分享SPDX哈

好咧，安排上～

**Comment by will-ww** [comment]
> 议题持续征集中：
> 
> 1. 企业开源实践：[Enterprise Open Source A Practical Introduction #42](https://github.com/kaiyuanshe/ONES/discussions/42)
> 
> * 提议人：@wangleo61
> * 主讲人：@will-ww （15分钟）
> 
> 2. SPDX 分享（15分钟）
> 
> * 主讲人： @wangleo61
> 
> 欢迎大家报名~

日程已更新了，第二次会议的议题已满，永雷老师有什么好的资料可以提前发出来哈~ @wangleo61 

还有新的议题我们就放到第三周了~

**Comment by will-ww** [comment]
每次我们可以留 15 分钟的自由讨论环节，这样一共 45 分钟，比较恰当~ @Nliver

**Comment by Nliver** [comment]
> 每次我们可以留 15 分钟的自由讨论环节，这样一共 45 分钟，比较恰当~ @Nliver

好的~

**Comment by will-ww** [comment]
还有几个日常事物和大家 update，可以一并加进去放到第 3 部分：
- 社区 logo 的设计与投票 #19
- 成员加入的流程与机制 #7 #10 
- ONES Newsletter #41 

@Nliver

**Comment by will-ww** [comment]
> > @will-ww 我可以花15分钟跟大家分享SPDX哈
> 
> 好咧，安排上，那企业开源实践就我来分享吧～

由于下周要开开源治理标准会的讨论会了，临时将本周的第一个议题成治理框架了~

这个我们就安排到下次了哈：https://github.com/kaiyuanshe/ONES/discussions/42

**Comment by wangleo61** [comment]
好的，王老师，那SPDX也是推迟到下次么？


发件人: Will ***@***.***>
发送时间: Wednesday, March 23, 2022 9:56 AM
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [kaiyuanshe/ONES] [会议] 2022 年 3 月 27 日第二次线上工作会议 (Issue #44)


@will-ww<https://github.com/will-ww> 我可以花15分钟跟大家分享SPDX哈

好咧，安排上，那企业开源实践就我来分享吧～

由于下周要开开源治理标准会的讨论会了，临时将本周的第一个议题成治理框架了~

这个我们就安排到下次了哈：#42<https://github.com/kaiyuanshe/ONES/discussions/42>

―

**Comment by wangleo61** [comment]
好的，收到，多谢王老师

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送


________________________________
发件人: Will Wang ***@***.***>
发送时间: Saturday, March 26, 2022 9:38:02 PM
收件人: kaiyuanshe/ONES ***@***.***>
抄送: wangleo61 ***@***.***>; Mention ***@***.***>
主题: Re: [kaiyuanshe/ONES] [会议] 2022 年 3 月 27 日第二次线上工作会议 (Issue #44)


议题持续征集中：

  1.  开源善治理首创行动分享

  *   ***@***.***<https://github.com/will-ww>
  *   ***@***.***<https://github.com/will-ww> （15分钟）

  1.  SPDX 分享（15分钟）

  *   主讲人： @wangleo61<https://github.com/wangleo61>

  1.  ONES 日常事务（3分钟）

欢迎大家报名~

明天晚上晚上 9:0010:00，我们继续第二次哈 @Nliver<https://github.com/Nliver> @wangleo61<https://github.com/wangleo61>

会议主题：ONES 双周例会
会议时间：2022/03/27 21:00-22:00 (GMT+08:00) 中国标准时间 - 北京
重复周期：2022/03/27-2024/02/11 21:00-22:00, 每两周 (周日)

#腾讯会议：793-2266-7523

欢迎大家参加~

―

**Comment by will-ww** [comment]
w晚上要分享的资料：

[03-27 开源善制首创行动规范指南.pdf](https://github.com/kaiyuanshe/ONES/files/8356668/03-27.pdf)

**Comment by Nliver** [comment]
> > 议题持续征集中：
> > 
> > 1. 开源善治理首创行动分享
> > 
> > 
> > * 提议人：@will-ww
> > * 主讲人：@will-ww （15分钟）
> > 
> > 
> > 2. SPDX 分享（15分钟）
> > 
> > 
> > * 主讲人： @wangleo61
> > 
> > 
> > 3. ONES 日常事务（3分钟）
> > 
> > 欢迎大家报名~
> 
> 明天晚上晚上 9:00 ~ 10:00，我们继续第二次哈~ @Nliver @wangleo61
> 
> 会议主题：**ONES 双周例会** 会议时间：2022/03/27 21:00-22:00 重复周期：2022/03/27-2024/02/11 21:00-22:00, 每两周 (周日)
> 
> #腾讯会议：793-2266-7523
> 
> 欢迎大家参加~



> > 议题持续征集中：
> > 
> > 1. 开源善治理首创行动分享
> > 
> > 
> > * 提议人：@will-ww
> > * 主讲人：@will-ww （15分钟）
> > 
> > 
> > 2. SPDX 分享（15分钟）
> > 
> > 
> > * 主讲人： @wangleo61
> > 
> > 
> > 3. ONES 日常事务（3分钟）
> > 
> > 欢迎大家报名~
> 
> 明天晚上晚上 9:00 ~ 10:00，我们继续第二次哈~ @Nliver @wangleo61
> 
> 会议主题：**ONES 双周例会** 会议时间：2022/03/27 21:00-22:00 重复周期：2022/03/27-2024/02/11 21:00-22:00, 每两周 (周日)
> 
> #腾讯会议：793-2266-7523
> 
> 欢迎大家参加~

收到

**Comment by Nliver** [comment]
> > 议题持续征集中：
> > 
> > 1. 开源善治理首创行动分享
> > 
> > 
> > * 提议人：@will-ww
> > * 主讲人：@will-ww （15分钟）
> > 
> > 
> > 2. SPDX 分享（15分钟）
> > 
> > 
> > * 主讲人： @wangleo61
> > 
> > 
> > 3. ONES 日常事务（3分钟）
> > 
> > 欢迎大家报名~
> 
> 明天晚上晚上 9:00 ~ 10:00，我们继续第二次哈~ @Nliver @wangleo61
> 
> 会议主题：**ONES 双周例会** 会议时间：2022/03/27 21:00-22:00 重复周期：2022/03/27-2024/02/11 21:00-22:00, 每两周 (周日)
> 
> #腾讯会议：793-2266-7523
> 
> 欢迎大家参加~
收到

**Comment by will-ww** [comment]
第二次会议视频已上传：https://www.bilibili.com/video/BV1Ru411v7BW?share_source=copy_web

谢谢~ @Nliver

**Comment by wangleo61** [comment]
给力

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Will Wang ***@***.***>
发送时间: Sunday, March 27, 2022 10:33:40 PM
收件人: kaiyuanshe/ONES ***@***.***>
抄送: wangleo61 ***@***.***>; Mention ***@***.***>
主题: Re: [kaiyuanshe/ONES] [会议] 2022 年 3 月 27 日第二次线上工作会议 (Issue #44)


第二次会议视频已上传：https://www.bilibili.com/video/BV1Ru411v7BW?share_source=copy_web

谢谢~ @Nliver<https://github.com/Nliver>

―

**Comment by Nliver** [comment]
本次会议已圆满结束~

**Comment by Nliver** [comment]
会议报道：https://mp.weixin.qq.com/s/Mn5n_3SagS4Z-cu6ODrAjg
会议回放：https://www.bilibili.com/video/BV1Ru411v7BW

**Comment by wangleo61** [comment]
期待王老师的分享

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Will ***@***.***>
发送时间: Sunday, March 27, 2022 9:41 AM
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [kaiyuanshe/ONES] [会议] 2022 年 3 月 27 日第二次线上工作会议 (Issue #44)


w晚上要分享的资料：

03-27 开源善制首创行动规范指南.pdf<https://github.com/kaiyuanshe/ONES/files/8356668/03-27.pdf>

―
