### ISSUE TITLE
ONES Group 官方网站建设

### ISSUE THREAD

**Issue by will-ww** [kaiyuanshe/ONES#53]
我们将利用 GitHub pages 功能，同时借助一些模板，开发 ONES Group 的官方网站，大家可以提出一些建议。

模板参考：
- https://jekyllthemes.io/theme/vonge
- https://jamstackthemes.dev/demo/theme/bulma-clean-theme/
- https://jamstackthemes.dev/demo/theme/jekyll-theme-mundana/

结构参考：https://todogroup.org/

@zhuangbiaowei @zhicheng-ning

**Comment by zhicheng-ning** [comment]
------
Completed Tasks：
- [X] Getting started with github pages
- [X] Configure a custom domain name
- [X] Enforce HTTPS
- [X] Getting started with GitHub pages, writing a simple demo website：https://ones.nzcer.cn/
------
What to do next：
- [ ] Getting started with Jekyll
- [ ] Find a theme that is functional and beautiful
- [ ] Practice to complete the deployment of the official website of ONES GROUP

**Comment by will-ww** [comment]
> Completed Tasks：
> 
> * [x]  Getting started with github pages
> * [x]  Configure a custom domain name
> * [x]  Enforce HTTPS
> * [x]  Getting started with GitHub pages, writing a simple demo website：https://ones.nzcer.cn/
> 
> What to do next：
> 
> * [ ]  Getting started with Jekyll
> * [ ]  Find a theme that is functional and beautiful
> * [ ]  Practice to complete the deployment of the official website of ONES GROUP

@zhicheng-ning 做的不错，庄老师可以多来指导下了~ @zhuangbiaowei

**Comment by zhicheng-ning** [comment]
@will-ww @zhuangbiaowei 
The demo website is https://blog.nzcer.cn/.
How is the style of this theme？How do you think ? 

------
Completed Tasks：
- [X] Getting started with Jekyll. [Reference documentation](https://jekyllrb.com/docs/step-by-step/01-setup/)
- [X] Find a theme that is functional and beautiful
- [X] Practice to complete the deployment of the official website of ONES GROUP
------
What to do next：
- [ ] Refactor website pages to fit into  our Ones Group website
- [ ] Refactor the project code
- [ ] Add new features

**Comment by will-ww** [comment]
> @will-ww @zhuangbiaowei The demo website is https://blog.nzcer.cn/. How is the style of this theme？How do you think ?
> 
> Completed Tasks：
> 
> * [x]  Getting started with Jekyll. [Reference documentation](https://jekyllrb.com/docs/step-by-step/01-setup/)
> * [x]  Find a theme that is functional and beautiful
> * [x]  Practice to complete the deployment of the official website of ONES GROUP
> 
> What to do next：
> 
> * [ ]  Refactor website pages to fit into  our Ones Group website
> * [ ]  Refactor the project code
> * [ ]  Add new features


https://blog.nzcer.cn/

好像访问不了呢？@zhicheng-ning

**Comment by zhicheng-ning** [comment]
> > @will-ww @zhuangbiaowei The demo website is https://blog.nzcer.cn/. How is the style of this theme？How do you think ?
> > Completed Tasks：
> > 
> > * [x]   Getting started with Jekyll. [Reference documentation](https://jekyllrb.com/docs/step-by-step/01-setup/)
> > * [x]   Find a theme that is functional and beautiful
> > * [x]   Practice to complete the deployment of the official website of ONES GROUP
> > 
> > What to do next：
> > 
> > * [ ]   Refactor website pages to fit into  our Ones Group website
> > * [ ]   Refactor the project code
> > * [ ]   Add new features
> 
> 可以了，稍微慢点，我觉得可以，然后开始填充内容进去了~
> 
> 大家可以来看看~ @zhuangbiaowei @Nliver

1. For the filling of website content, just add content similar to the following at the top of each markdown file. The following content shows the blog post's title, author, category, tags and other attributes.
```
---
layout: post
title:  "Powerful things you can do with the Markdown editor"
author: sal
categories: [ Jekyll, tutorial ]
image: assets/images/4.jpg
tags: [featured]
---
```
2. If you need to change the custom domain name to ones.kaiyuanshe.com, the person in charge of domain name management needs to connect with me.

**Comment by wangleo61** [comment]
给力呀

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: 逝不等琴生 ***@***.***>
发送时间: Friday, April 8, 2022 10:06:07 AM
收件人: kaiyuanshe/ONES ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [kaiyuanshe/ONES] ONES Group 官方网站建设 (Issue #53)


@will-ww<https://github.com/will-ww> @zhuangbiaowei<https://github.com/zhuangbiaowei> The demo website is https://blog.nzcer.cn/. How is the style of this theme？How do you think ?
Completed Tasks：

  *    Getting started with Jekyll. Reference documentation<https://jekyllrb.com/docs/step-by-step/01-setup/>
  *    Find a theme that is functional and beautiful
  *    Practice to complete the deployment of the official website of ONES GROUP

What to do next：

  *    Refactor website pages to fit into our Ones Group website
  *    Refactor the project code
  *    Add new features

可以了，稍微慢点，我觉得可以，然后开始填充内容进去了~

大家可以来看看~ @zhuangbiaowei<https://github.com/zhuangbiaowei> @Nliver<https://github.com/Nliver>

  1.  For the filling of website content, just add content similar to the following at the top of each markdown file. The following content shows the blog post's title, author, category, tags and other attributes.

---

layout: post

title:  "Powerful things you can do with the Markdown editor"

author: sal

categories: [ Jekyll, tutorial ]

image: assets/images/4.jpg

tags: [featured]

---



  1.  If you need to change the custom domain name to ones.kaiyuanshe.com, the person in charge of domain name management needs to connect with me.

―

**Comment by TechQuery** [comment]
开源社 2022 版官网已支持 Markdown 渲染技术，可通过 Git submodule 实现本仓库的文献发布：

- 原始 issue：kaiyuanshe/kaiyuanshe.github.io#42
- 效果演示：https://next-bootstrap-ts.vercel.app/article

**Comment by TechQuery** [comment]
开源社官网已自动生成部门主页，请在执委会飞书群公告中的表单链接填写 OKR 和 4P 报告来更新内容：
- 入口：https://kaiyuanshe.cn/department/ONES%20%E5%BC%80%E6%BA%90%E7%A0%94%E7%A9%B6%E6%88%98%E7%95%A5%E7%BB%84/2019
- 代码：kaiyuanshe/kaiyuanshe.github.io#332
