### ISSUE TITLE
[Outreach] 成为 TODO 2022 State of the OSPO Study 合作伙伴

### ISSUE THREAD

**Issue by xiaoya-Esther** [kaiyuanshe/ONES#55]
TODO Group 和 Linux Foundation Research 今年对 OSPO 的研究报告工作在[征集一些合作伙伴](https://todogroup.org/blog/partners-in-2022-state-of-the-ospo-study/)，具体见：

我们可以在3月28日～4月1日之间定一个时间和负责人 Hilary 聊一下具体参与与合作事宜，我创建了一个 [Doodle](https://doodle.com/meeting/participate/id/0dNgqK8e)，大家可以选择一下可以参与的时间，支持多选。

![image](https://user-images.githubusercontent.com/56542972/159008320-7a5ad401-786d-42f9-b026-9e4d7cc3b05c.png)

**Comment by will-ww** [comment]
Fantastic, many thanks~ @xiaoya-Esther

**Comment by xiaoya-Esther** [comment]
去年的 Study 报告成果供参考
[TODO OSPO.pdf](https://github.com/kaiyuanshe/ONES/files/8304762/TODO.OSPO.pdf)

**Comment by xiaoya-Esther** [comment]
Hilary 已经 check 时间，我们再定一个最终时间吧：https://doodle.com/meeting/organize/id/0dNgqK8e

**Comment by will-ww** [comment]
> Hilary 已经 check 时间，我们再定一个最终时间吧：https://doodle.com/meeting/organize/id/0dNgqK8e

已投~

**Comment by wangleo61** [comment]
Can I join?

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Xiaoya ***@***.***>
发送时间: Monday, March 21, 2022 10:18:57 PM
收件人: kaiyuanshe/ONES ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [kaiyuanshe/ONES] [Outreach] 成为 TODO 2022 State of the OSPO Study 合作伙伴 (Issue #55)


Hilary 已经 check 时间，我们再定一个最终时间吧：https://doodle.com/meeting/organize/id/0dNgqK8e

―

**Comment by xiaoya-Esther** [comment]
> Can I join? 从 Windows 版邮件<[https://go.microsoft.com/fwlink/?LinkId=550986>发送](https://go.microsoft.com/fwlink/?LinkId=550986>%E5%8F%91%E9%80%81)

Welcome!

**Comment by wangleo61** [comment]
Thanks xiaoya

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Xiaoya ***@***.***>
发送时间: Tuesday, March 22, 2022 10:10:32 AM
收件人: kaiyuanshe/ONES ***@***.***>
抄送: wangleo61 ***@***.***>; Comment ***@***.***>
主题: Re: [kaiyuanshe/ONES] [Outreach] 成为 TODO 2022 State of the OSPO Study 合作伙伴 (Issue #55)


Can I join? 从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送<https://go.microsoft.com/fwlink/?LinkId=550986%3E%E5%8F%91%E9%80%81>

Welcome!

―

**Comment by xiaoya-Esther** [comment]
### OSPO research partnership discussion
#### Time: Thu Mar 31, 2022 21:00 – 21:45 (Hong Kong Standard Time)
#### Join Zoom Meeting
[zoom.us/j/93060391918](https://zoom.us/j/93060391918) (ID: 93060391918)
Join by phone
(US) [+1 855-703-8985](tel:+18557038985,,93060391918#)
(US) [+1 855-880-1246](tel:+18558801246,,93060391918#)

#### Meeting host: [hcarter@linuxfoundation.org](mailto:hcarter@linuxfoundation.org)

**Comment by takasumasakazu** [comment]
好的，我也加了TODO group slack.下次都一起谈谈吧

**Comment by wangleo61** [comment]
期待

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: TAKASU Masakazu ***@***.***>
发送时间: Monday, April 11, 2022 12:27:07 AM
收件人: kaiyuanshe/ONES ***@***.***>
抄送: wangleo61 ***@***.***>; Comment ***@***.***>
主题: Re: [kaiyuanshe/ONES] [Outreach] 成为 TODO 2022 State of the OSPO Study 合作伙伴 (Issue #55)


好的，我也加了TODO group slack.下次都一起谈谈吧

―

**Comment by xiaoya-Esther** [comment]
The discussion meeting was successfully held in Mar 23.
