### ISSUE TITLE
[会议] 2022 年 4 月 24 日第三次线上工作会议

### ISSUE THREAD

**Issue by will-ww** [kaiyuanshe/ONES#59]
议题持续征集中：

1. 开源 + 数字一带一路
- 提议人&主讲人：张国锋（15分钟）

2. NFT和开发者激励
- 提议人&主讲人：宋青见（15分钟）

欢迎大家报名~

**Comment by wangleo61** [comment]
期待哈

**Comment by will-ww** [comment]
由于疫情原因，我们推迟到到两周后的 24 号吧~

**Comment by wangleo61** [comment]
好的，收到

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Will ***@***.***>
发送时间: Sunday, April 10, 2022 9:32 AM
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [kaiyuanshe/ONES] [会议] 2022 年 4 月 24 日第三次线上工作会议 (Issue #59)


由于疫情原因，我们推迟到到两周后的 24 号吧~

―

**Comment by will-ww** [comment]
> 2. NFT和开发者激励
>    提议人&主讲人：宋青见（15分钟）

欢迎！

**Comment by wangleo61** [comment]
期待

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Will Wang ***@***.***>
发送时间: Sunday, April 17, 2022 9:18:42 PM
收件人: kaiyuanshe/ONES ***@***.***>
抄送: wangleo61 ***@***.***>; Comment ***@***.***>
主题: Re: [kaiyuanshe/ONES] [会议] 2022 年 4 月 24 日第三次线上工作会议 (Issue #59)


  1.  NFT和开发者激励
提议人&主讲人：宋青见（15分钟）

欢迎！

―

**Comment by Nliver** [comment]
本次会议已圆满结束~
