### ISSUE TITLE
[Help] 如何将 Google 日历集成到 ONES 下面

### ISSUE THREAD

**Issue by will-ww** [kaiyuanshe/ONES#60]
我们需要一个日历来分享社区的活动，方便大家追踪安排，例如：https://todogroup.org/community/

![image](https://user-images.githubusercontent.com/15010826/159167789-d56e1503-8e27-4cdd-906c-705afc716811.png)

大家有什么好的解决方案不？例如把 Google 日历集成到 GitHub 的页面上面？

**Comment by TechQuery** [comment]
经**开源社媒体组**发布的**活动推文**，均可展示在官网**活动日历**：
- 入口：https://kaiyuanshe.cn/activity/calendar
- 代码：kaiyuanshe/kaiyuanshe.github.io#183
