### ISSUE TITLE
准备报一个 ApacheCon Asia 2022 演讲提案

### ISSUE THREAD

**Issue by will-ww** [kaiyuanshe/ONES#84]
准备报一个 ApacheCon Asia 2022 演讲提案：https://www.apachecon.com/acasia2022/

- 类型：圆桌论坛
- 主题：社区
- 题目：开源社区治理与运营之道 —— ONES Group 的实践（暂定）
- 讲师：待定

欢迎感兴趣的报名或提出建议~

**Comment by wangleo61** [comment]
可以推荐王老师么

Leo

发件人: Will ***@***.***>
发送时间: Tuesday, May 10, 2022 10:47 AM
收件人: ***@***.***>
抄送: ***@***.***>
主题: [kaiyuanshe/ONES] 准备报一个 ApacheCon Asia 2022 演讲提案 (Issue #84)


准备报一个 ApacheCon Asia 2022 演讲提案：https://www.apachecon.com/acasia2022/

  *   类型：圆桌论坛
  *   主题：社区
  *   题目：开源社区治理与运营之道 ―― ONES Group 的实践（暂定）
  *   讲师：待定

欢迎感兴趣的报名或提出建议~

―

**Comment by will-ww** [comment]
一起一起~
